### ISSUE TITLE
uninitialized constant & multiline regex match issue

### ISSUE THREAD

**Issue by Dutzu** [kiyoto/fluent-plugin-grok-parser#13]
Hello,

When trying to use the plugin without multiline I always get this error:

```ruby
2015-12-09 16:36:03 +0200 [error]: unexpected error error="uninitialized constant Fluent::TextParser::MultilineGrokParser"
  2015-12-09 16:36:03 +0200 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-grok-parser-0.0.3/lib/fluent/plugin/grok.rb:23:in `initialize'
  2015-12-09 16:36:03 +0200 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-grok-parser-0.0.3/lib/fluent/plugin/parser_grok.rb:21:in `new'
  2015-12-09 16:36:03 +0200 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-grok-parser-0.0.3/lib/fluent/plugin/parser_grok.rb:21:in `configure'
```

And when running in multiline mode, no matter how and what regex pattern I set for detecting a new log message I always get this error:

`2015-12-09 16:39:26 +0200 [error]: empty range in char class: ` followed by the log line it had read.
The source seems to be the following:
```ruby
2015-12-09 16:39:26 +0200 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-grok-parser-0.0.3/lib/fluent/plugin/parser_multiline_grok.rb:23:in `match'
  2015-12-09 16:39:26 +0200 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-grok-parser-0.0.3/lib/fluent/plugin/parser_multiline_grok.rb:23:in `firstline?'
  2015-12-09 16:39:26 +0200 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin/in_tail.rb:266:in `block in parse_multilines'
```

Keep in mind, running it without setting the `multiline_start_regexp` will work, of course without benefiting from the multiline aggregation functionality.

Also please fix the typo in the example config you have in the Readme because there you specify the parameter as being `multiline_start_regex`, without a `p` in the end, which basically makes the plugin run without the multi line detection.

Thanks

P.S. - for reference:
* td-agent v0.12.12
* fluentd v0.12.17
* fluent-plugin-grok-parser v0.0.3
* ruby 1.9.3p484

running on Linux Mint 17.2 (Ubuntu 14.04.2 LTS Trusty)

**Comment by okkez** [comment]
Thank you for reporting issue.
I've fixed uninitialized constant error and typos in README.md.
But I cannot reproduce `[error]: empty range in char class:`

Please show me your fluent.conf and sample input.

**Comment by Dutzu** [comment]
Hi,

Here, Try this:

```ruby
<source>
  type tail
  path /var/log/test.log
  read_from_head true
  tag test.unprocessed

  format multiline_grok
  multiline_start_regexp /^\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}[,.]\d{3}/

  grok_pattern 20%{YEAR:year}-%{MONTHNUM2}-%{MONTHDAY} %{TIME},(\d{3})
</source>

<match **>
  type stdout
</match>
```

Test input:
```ruby
2015-10-15 06:34:01,471 [test] LogInterceptor                 INFO  ==== Request ===
2015-10-15 06:34:01,473 [test-ajp] LogInterceptor                 INFO  GET /monitor/broker/ HTTP/1.1
```

Seems that weirdly enough the problem is with the threadname part of the log, and if you have a minus sign in there you get the error, if not, you don't :)
So, the line with `[test]` will go ok and the line with `[test-ajp]` won't. If you remove the minus sign and change it to `[testajp]` it will work again. 

Hope this helps.

**Comment by okkez** [comment]
Thank you for more info.
I will check in next week.

**Comment by okkez** [comment]
Thank you. I've fixed problems and released new version.
